---

#++++++++++++++++++++++++++++
# ANSIBLE SECTION
# You probably don't need to adjust this
#++++++++++++++++++++++++++++
ansible:
  host_key_checking: false
  raw_env_vars:
    ANSIBLE_FORCE_COLOR: true
  env:
    ANSIBLE_ROLES_PATH: ../resources/roles
    ANSIBLE_SSH_RETRIES: '5'
    ANSIBLE_CALLBACK_WHITELIST: "junit"
    ANSIBLE_CALLBACK_PLUGINS: $PWD/molecule/resources/callback_plugins
    JUNIT_OUTPUT_DIR: $PWD/molecule/reports
    JUNIT_INCLUDE_SETUP_TASKS_IN_REPORT: false
  ansiblecfg_defaults:
    retry_files_enabled: false
    callback_whitelist: junit


#++++++++++++++++++++++++++++
# DEPENDENCY SECTION
# 1. Use galaxy for the standard molecule way
# 2. Use the shell/pymgit method for custom molecule delegated drivers (full VMs)
# NOTICE: if requirements are scenario-dependent, then needs to be defined
# in molecule.yml in each scenario
#++++++++++++++++++++++++++++

# 1. Galaxy
# dependency:
#   name: galaxy
#   enabled: True
#   options:
#     ignore-errors: true
#     ignore-certs: true
#     roles-path: $PWD/molecule/resources/roles
#     role-file: $PWD/molecule/default/requirements.yml

# 2. Pymgit
dependency:
  name: shell
  enabled: True
  command: pymgit -f -s -r molecule/shared/requirements.yml


#++++++++++++++++++++++++++++
# DRIVER SECTION
# 1. Use docker if you can
# 2. Use the custom delegated/pymgit method (full VMs)
#++++++++++++++++++++++++++++

# 1. Docker
# driver:
#   name: docker

# 2. Custom delegated
driver:
  name: delegated
  options:
    managed: true
    login_cmd_template: 'ssh {instance} -F {{ molecule_ephemeral_directory }}/ssh_config'
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: '-F {{ molecule_ephemeral_directory }}/ssh_config'


#++++++++++++++++++++++++++++
# YAML LINT SECTION
# You probably don't need to adjust this
#++++++++++++++++++++++++++++
lint:
  name: yamllint
  enabled: true
  options:
    config-file: .yamllint


#++++++++++++++++++++++++++++
# PLATFORMS SECTION
# change *role_template* and *-role-template-* to corresponde with your role name
# 1. Use docker if you can.  May need to specify other images for special cases
# 2. Use the custom delegated/pymgit method (full VMs)
#++++++++++++++++++++++++++++
# platforms must be defined in molecule.yml in each scenario


#++++++++++++++++++++++++++++
# PROVISIONER SECTION
# You'll need to define any role vars here that you want to specifically test
# in your scenario
#++++++++++++++++++++++++++++
# the provisionor sections is likecly scenario-dependent and therefore should be
# defined in molecule.yml in each scenario.  If not, it could be defined here
provisioner:
  name: ansible
  inventory:
    group_vars:
      azure:
        molecule_create_strategy: linear
        molecule_destroy_strategy: linear
  playbooks:
    delegated:
      create: ../resources/playbooks/create.yml
      destroy: ../resources/playbooks/destroy.yml
  env:
    ANSIBLE_ROLES_PATH: ../resources/roles
    ANSIBLE_SSH_RETRIES: '5'
    ANSIBLE_CALLBACK_WHITELIST: "junit"
    ANSIBLE_CALLBACK_PLUGINS: $PWD/molecule/resources/callback_plugins
    JUNIT_OUTPUT_DIR: $PWD/molecule/reports
    JUNIT_INCLUDE_SETUP_TASKS_IN_REPORT: false
  lint:
    name: ansible-lint
    enabled: true  # need to disable until we fully move to 2.9+ as testing with 2.8 fails
    options:
      exclude:
        - molecule/resources/
        - tasks/azure_2.9.yml
        - tasks/vmware_2.9.yml


#++++++++++++++++++++++++++++
# SCENARIO SECTION
# You probably don't need to adjust this (unless you're created another scenario)
#++++++++++++++++++++++++++++
# since scenario name is in this section, needs to be in molecule.yml


#++++++++++++++++++++++++++++
# VERIFIER SECTION
# You probably don't need to adjust this (unless you're created another scenario)
#++++++++++++++++++++++++++++
verifier:
# 1. Ansible verify
  name: ansible
  enabled: true
  lint:
    name: ansible-lint
    options:
      force-color: true
      x: ["305,602"]

# 2. Testinfra
# name: testinfra
# directory: tests/
# options:
#   junitxml: ../reports/junit-default-out.xml
#   vv: true  # more verbose output
#   # s: true  # see lots of output
# lint:
#   name: flake8
